// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wocqixwoabygddwbscct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvY3FpeHdvYWJ5Z2Rkd2JzY2N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzODAwOTEsImV4cCI6MjA2OTk1NjA5MX0.ldpE2kxgSr3Su6c_GxoqvBQeLwGOhGjmSTYiLtKyuVM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});